language: ruby
cache:
  bundler: true
  directories:
    - "travis_phantomjs"
bundler_args: --without development doc
sudo: false
addons:
  postgresql: "9.4"
services:
  - postgresql
before_install: # Install PhantomJS 2.1.1 or some of our specs fail with default (v1.9.8 as of 3/2/2017)
  - gem update bundler --no-rdoc --no-ri
  - "export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec
rvm:
  - 2.2.0
env:
  global:
    - MADELINE_EMAIL_FROM=madeline@theworkingworld.org
    - MADELINE_HOSTNAME=madeline.theworkingworld.org
